# Generated by Django 4.1.7 on 2023-04-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Sell date')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Client first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Client last name')),
                ('address', models.CharField(max_length=300, verbose_name='Client address')),
                ('phone', models.IntegerField(verbose_name='Client phone')),
                ('mail', models.CharField(max_length=100, verbose_name='Client e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Payment method')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('description', models.CharField(max_length=300, verbose_name='Category description')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product name')),
                ('image', models.CharField(max_length=300, verbose_name='Product image')),
                ('stock', models.IntegerField(default=0, verbose_name='Product stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware_store.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Product quantity')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware_store.bill')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware_store.product')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware_store.client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware_store.paymentmethod'),
        ),
    ]
