# Generated by Django 4.1.7 on 2023-11-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=300, upload_to='', verbose_name='Product image'),
        ),
    ]
