# Generated by Django 4.1.7 on 2023-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0005_cart_products_cart_quantity_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Product quantity'),
        ),
    ]
